DROP VIEW vwClinicalMisc;
CREATE OR REPLACE VIEW vwClinicalMisc AS 
SELECT 
tblshared_bcr_patient_uuid_valuecolumn AS pat_uuid,
to_date(concat(tblshared_year_of_form_completion_valuecolumn,
	to_char(tblshared_month_of_form_completion_valuecolumn, '09'),
	to_char(tblshared_day_of_form_completion_valuecolumn, '09')), 'YYYY MM DD') AS form_complete_date,
tblshared_stage_system_version_valuecolumn,
tblshared_stage_pathologic_stage_valuecolumn,
tblshared_stage_pathologic_t_valuecolumn,
tblshared_stage_pathologic_n_valuecolumn,
tblshared_stage_pathologic_m_valuecolumn,
tblbrca_breast_cancer_surgery_margin_status_valuecolumn AS breast_cancer_surgery_margin_status,
tblbrca_axillary_lymph_node_stage_method_type_valuecolumn AS axillary_lymph_node_stage_method_type_iffy,
tblbrca_axillary_lymph_node_stage_other_method_descriptive_text_valuecolumn AS axillary_lymph_node_stage_other_method_descriptive_text_iffy,
tblbrca_distant_metastasis_present_ind2_valuecolumn AS distant_metastasis_present_ind2,
tblbrca_first_nonlymph_node_metastasis_anatomic_site_valuecolumn AS first_nonlymph_node_metastasis_anatomic_site,
tblbrca_shared_breast_carcinoma_estrogen_receptor_status_valuecolumn AS breast_carcinoma_estrogen_receptor_status,
tblbrca_shared_breast_carcinoma_immunohistochemistry_pos_cell_score_valuecolumn AS breast_carcinoma_immunohistochemistry_postitive_cell_score_iffy,
tblbrca_shared_breast_carcinoma_progesterone_receptor_status_valuecolumn AS breast_carcinoma_progesterone_receptor_status,
tblbrca_shared_er_level_cell_percentage_category_valuecolumn AS er_level_cell_percentage_category,
tblbrca_shared_her2_erbb_pos_finding_cell_percent_category_valuecolumn AS her2_erbb_pos_finding_cell_percent_category,
tblbrca_shared_her2_immunohistochemistry_level_result_valuecolumn AS her2_immunohistochemistry_level_result,
tblbrca_shared_her2_neu_and_centromere_17_copy_number_analysis_input_total_number_count_valuecolumn AS shared_her2_neu_and_centromere_17_copy_number_analysis_input_total_number_count,
tblbrca_shared_her2_neu_and_centromere_17_copy_number_metastatic_breast_carcinoma_analysis_input_total_number_count_valuecolumn
tblbrca_shared_her2_neu_breast_carcinoma_copy_analysis_input_total_number_count_valuecolumn,
tblbrca_shared_her2_neu_chromosone_17_signal_ratio_value_valuecolumn,
tblbrca_shared_her2_neu_metastatic_breast_carcinoma_copy_analysis_input_total_number_valuecolumn,
tblbrca_shared_immunohistochemistry_positive_cell_score_valuecolumn,
tblbrca_shared_lab_proc_her2_neu_immunohistochemistry_receptor_status_valuecolumn,
tblbrca_shared_lab_procedure_her2_neu_in_situ_hybrid_outcome_type_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_erbb2_immunohistochemistry_level_result_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_level_cell_percent_category_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_status_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_fluorescence_in_situ_hybridization_diagnostic_proc_centromere_17_signal_result_range_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_her2_erbb_pos_finding_cell_percent_category_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_her2_neu_chromosone_17_signal_ratio_value_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_pos_cell_score_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_positive_finding_scale_type_valuecolumn AS tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_positive_finding_scale_type_iffy,
tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_pr_pos_cell_score_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_progesterone_receptor_positive_finding_scale_type_valuecolumn AS tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_progesterone_receptor_positive_finding_scale_type_iffy,
tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_immunohistochemistry_receptor_status_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_in_situ_hybridization_outcome_type_valuecolumn AS tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_in_situ_hybridization_outcome_type_iffy,
tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_level_cell_percent_category_valuecolumn,
tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_status_valuecolumn,
tblbrca_shared_progesterone_receptor_level_cell_percent_category_valuecolumn,
tblbrca_surgical_procedure_purpose_other_text_valuecolumn,
tblnte_additional_pharmaceutical_therapy_valuecolumn,
tblnte_additional_radiation_therapy_valuecolumn,
tblnte_additional_surgery_locoregional_procedure_valuecolumn,
tblnte_days_to_additional_surgery_locoregional_procedure_valuecolumn,
tblnte_days_to_additional_surgery_metastatic_procedure_valuecolumn,
tblnte_days_to_new_tumor_event_additional_surgery_procedure_valuecolumn,
tblnte_days_to_new_tumor_event_after_initial_treatment_valuecolumn,
tblnte_new_neoplasm_event_occurrence_anatomic_site_valuecolumn,
tblnte_new_neoplasm_event_type_valuecolumn,
tblnte_new_tumor_event_additional_surgery_procedure_valuecolumn,
tblnte_new_tumor_event_after_initial_treatment_valuecolumn
FROM tblbrca_patient
LEFT JOIN tblshared_bcr_patient_uuid 
	ON tblbrca_patient.tblbrca_patient_id_key = tblshared_bcr_patient_uuid.tblbrca_patient_id_key
LEFT JOIN tblbrca_breast_cancer_surgery_margin_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_breast_cancer_surgery_margin_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_axillary_lymph_node_stage_method_type
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_axillary_lymph_node_stage_method_type.tblbrca_patient_id_key
LEFT JOIN tblbrca_axillary_lymph_node_stage_other_method_descriptive_text
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_axillary_lymph_node_stage_other_method_descriptive_text.tblbrca_patient_id_key
LEFT JOIN tblbrca_distant_metastasis_present_ind2
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_distant_metastasis_present_ind2.tblbrca_patient_id_key
LEFT JOIN tblbrca_first_nonlymph_node_metastasis_anatomic_sites
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_first_nonlymph_node_metastasis_anatomic_sites.tblbrca_patient_id_key
LEFT JOIN tblbrca_first_nonlymph_node_metastasis_anatomic_site
	ON tblbrca_first_nonlymph_node_metastasis_anatomic_sites.tblbrca_first_nonlymph_node_metastasis_anatomic_sites_id_key
	= tblbrca_first_nonlymph_node_metastasis_anatomic_site.tblbrca_first_nonlymph_node_metastasis_anatomic_site_id_key
LEFT JOIN tblbrca_shared_breast_carcinoma_estrogen_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_breast_carcinoma_estrogen_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_breast_carcinoma_immunohistochemistry_pos_cell_score
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_breast_carcinoma_immunohistochemistry_pos_cell_score.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_breast_carcinoma_progesterone_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_breast_carcinoma_progesterone_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_er_level_cell_percentage_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_er_level_cell_percentage_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_erbb_pos_finding_cell_percent_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_erbb_pos_finding_cell_percent_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_immunohistochemistry_level_result
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_immunohistochemistry_level_result.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_neu_metastatic_breast_carcinoma_copy_analysis_input_total_number
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_neu_metastatic_breast_carcinoma_copy_analysis_input_total_number.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_neu_and_centromere_17_copy_number_analysis_input_total_number_count
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_neu_and_centromere_17_copy_number_analysis_input_total_number_count.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_neu_and_centromere_17_copy_number_metastatic_breast_carcinoma_analysis_input_total_number_count
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_neu_and_centromere_17_copy_number_metastatic_breast_carcinoma_analysis_input_total_number_count.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_her2_neu_chromosone_17_signal_ratio_value
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_her2_neu_chromosone_17_signal_ratio_value.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_immunohistochemistry_positive_cell_score
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_immunohistochemistry_positive_cell_score.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_lab_proc_her2_neu_immunohistochemistry_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_lab_proc_her2_neu_immunohistochemistry_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_lab_procedure_her2_neu_in_situ_hybrid_outcome_type
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_lab_procedure_her2_neu_in_situ_hybrid_outcome_type.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_erbb2_immunohistochemistry_level_result
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_erbb2_immunohistochemistry_level_result.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_level_cell_percent_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_level_cell_percent_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_estrogen_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_fluorescence_in_situ_hybridization_diagnostic_proc_centromere_17_signal_result_range
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_fluorescence_in_situ_hybridization_diagnostic_proc_centromere_17_signal_result_range.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_her2_erbb_pos_finding_cell_percent_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_her2_erbb_pos_finding_cell_percent_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_her2_neu_chromosone_17_signal_ratio_value
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_her2_neu_chromosone_17_signal_ratio_value.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_pos_cell_score
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_pos_cell_score.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_pr_pos_cell_score
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_pr_pos_cell_score.tblbrca_patient_id_key
LEFT JOIN tblbrca_nte_new_tumor_events
	ON tblbrca_patient.tblbrca_patient_id_key = tblbrca_nte_new_tumor_events.tblbrca_patient_id_key
LEFT JOIN tblbrca_nte_new_tumor_event
	ON tblbrca_nte_new_tumor_events.tblbrca_nte_new_tumor_events_id_key
	= tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_events_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_positive_finding_scale_type
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_er_positive_finding_scale_type.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_progesterone_receptor_positive_finding_scale_type
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_immunohistochemistry_progesterone_receptor_positive_finding_scale_type.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_immunohistochemistry_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_immunohistochemistry_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_in_situ_hybridization_outcome_type
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_lab_proc_her2_neu_in_situ_hybridization_outcome_type.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_level_cell_percent_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_level_cell_percent_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_status
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_metastatic_breast_carcinoma_progesterone_receptor_status.tblbrca_patient_id_key
LEFT JOIN tblbrca_shared_progesterone_receptor_level_cell_percent_category
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_shared_progesterone_receptor_level_cell_percent_category.tblbrca_patient_id_key
LEFT JOIN tblbrca_surgical_procedure_purpose_other_text
	ON tblbrca_patient.tblbrca_patient_id_key
	= tblbrca_surgical_procedure_purpose_other_text.tblbrca_patient_id_key
LEFT JOIN tblnte_additional_pharmaceutical_therapy
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key = tblnte_additional_pharmaceutical_therapy.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_additional_radiation_therapy
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key = tblnte_additional_radiation_therapy.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblbrca_follow_ups
	ON tblbrca_patient.tblbrca_patient_id_key = tblbrca_follow_ups_id_key
LEFT JOIN tblfollow_up_V2_1_follow_up
	ON tblbrca_follow_ups.tblbrca_follow_ups_id_key
	= tblfollow_up_V2_1_follow_up.tblbrca_follow_ups_id_key
LEFT JOIN tblfollow_up_V1_5_follow_up
	ON tblbrca_follow_ups.tblbrca_follow_ups_id_key
	= tblfollow_up_V1_5_follow_up.tblbrca_follow_ups_id_key
LEFT JOIN tblnte_additional_surgery_locoregional_procedure
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_additional_surgery_locoregional_procedure.tblfollow_up_V1_5_follow_up_id_key
LEFT JOIN tblnte_days_to_additional_surgery_locoregional_procedure
	ON tblfollow_up_V1_5_follow_up.tblfollow_up_V1_5_follow_up_id_key
	= tblnte_days_to_additional_surgery_locoregional_procedure.tblfollow_up_V1_5_follow_up_id_key
LEFT JOIN tblnte_days_to_additional_surgery_metastatic_procedure
	ON tblfollow_up_V1_5_follow_up.tblfollow_up_V1_5_follow_up_id_key
	= tblnte_days_to_additional_surgery_metastatic_procedure.tblfollow_up_V1_5_follow_up_id_key
LEFT JOIN tblnte_days_to_new_tumor_event_additional_surgery_procedure
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_days_to_new_tumor_event_additional_surgery_procedure.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_days_to_new_tumor_event_after_initial_treatment
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_days_to_new_tumor_event_after_initial_treatment.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_new_neoplasm_event_occurrence_anatomic_site
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_new_neoplasm_event_occurrence_anatomic_site.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_new_neoplasm_event_type
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_new_neoplasm_event_type.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_new_tumor_event_additional_surgery_procedure
	ON tblbrca_nte_new_tumor_event.tblbrca_nte_new_tumor_event_id_key
	= tblnte_new_tumor_event_additional_surgery_procedure.tblbrca_nte_new_tumor_event_id_key
LEFT JOIN tblnte_new_tumor_event_after_initial_treatment
	ON tblfollow_up_V2_1_follow_up.tblfollow_up_V2_1_follow_up_id_key
	= tblnte_new_tumor_event_after_initial_treatment.tblfollow_up_V2_1_follow_up_id_key
LEFT JOIN tblshared_day_of_form_completion
	ON tblbrca_patient.tblbrca_patient_id_key = tblshared_day_of_form_completion.tblbrca_patient_id_key
LEFT JOIN tblshared_month_of_form_completion
	ON tblbrca_patient.tblbrca_patient_id_key = tblshared_month_of_form_completion.tblbrca_patient_id_key
LEFT JOIN tblshared_year_of_form_completion
	ON tblbrca_patient.tblbrca_patient_id_key = tblshared_year_of_form_completion.tblbrca_patient_id_key
LEFT JOIN tblshared_stage_stage_event
	ON tblbrca_patient.tblbrca_patient_id_key = tblshared_stage_stage_event.tblbrca_patient_id_key
LEFT JOIN tblshared_stage_system_version
	ON tblshared_stage_system_version.tblshared_stage_stage_event_id_key
	= tblshared_stage_stage_event.tblshared_stage_stage_event_id_key
LEFT JOIN tblshared_stage_pathologic_stage
	ON tblshared_stage_pathologic_stage.tblshared_stage_stage_event_id_key
	= tblshared_stage_stage_event.tblshared_stage_stage_event_id_key
LEFT JOIN tblshared_stage_tnm_categories
	ON tblshared_stage_stage_event.tblshared_stage_stage_event_id_key
	= tblshared_stage_tnm_categories.tblshared_stage_stage_event_id_key
LEFT JOIN tblshared_stage_pathologic_categories
	ON tblshared_stage_tnm_categories.tblshared_stage_tnm_categories_id_key
	= tblshared_stage_pathologic_categories.tblshared_stage_tnm_categories_id_key
LEFT JOIN tblshared_stage_pathologic_t
	ON tblshared_stage_pathologic_categories.tblshared_stage_pathologic_categories_id_key
	= tblshared_stage_pathologic_t.tblshared_stage_pathologic_categories_id_key
LEFT JOIN tblshared_stage_pathologic_n
	ON tblshared_stage_pathologic_categories.tblshared_stage_pathologic_categories_id_key
	= tblshared_stage_pathologic_n.tblshared_stage_pathologic_categories_id_key
LEFT JOIN tblshared_stage_pathologic_m
	ON tblshared_stage_pathologic_categories.tblshared_stage_pathologic_categories_id_key
	= tblshared_stage_pathologic_m.tblshared_stage_pathologic_categories_id_key
--LIMIT 5
;